connect metrics api
DakoData/DakoData pull request #15
Opened 2021-02-04 12:39 UTC by ChiaEnC

## Why do we need this PR?
* connect metrics api to backend

## How did you address the issue?
* implement saga, reducer, and actions 

<br />  

> #### PR readiness check list
> - [ ] Did it pass the Flake8/Standard JS check?
> - [ ] Did you test this PR?  
> - [ ] Did you explain the changes clearly?
> - [ ] Does the PR title reference a Jira issue for the correct project (at the beginning of the title)?

2021-02-08 09:16 UTC, KalleChen approved these changes

2021-02-08 09:25 UTC, amjltc295 requested changes

2021-02-08 09:25 UTC, amjltc295 commented on backend/app/app/crud/crud_metrics.py
> +            Customer.created_at <= datetime.strptime(metrics_in.start_time, "%Y-%m-%d"),
Use dateutil.parser.parse()

2021-02-08 09:25 UTC, amjltc295 commented on website/src/api/fetch.js
> +        console.log(typeof obj['start_time']);
Please remove this debugging message

2021-02-08 09:25 UTC, amjltc295 commented on website/src/logged_in/views/dashboard/Dashboard.js
> +  params['start_time'] = '2019-06-02';
We should set start_time by current time

2021-02-08 09:25 UTC, amjltc295 commented on website/src/logged_in/views/dashboard/Dashboard.js
> +  params['platform_id'] = 2
Why is this platform_id hard-coded?

2021-02-08 09:58 UTC, amjltc295 commented on backend/app/app/schemas/metrics.py
> +    end_time: str
If you need to change this type, please add a validation function

2021-02-13 14:43 UTC, amjltc295 requested changes

2021-02-13 14:43 UTC, amjltc295 commented on website/src/sagas/metricsSaga.js
> +} else if (error) {
Indentation here seems weird

2021-02-13 14:43 UTC, amjltc295 commented on backend/app/app/schemas/metrics.py
> +    end_time: str
This is not fixed yet?

2021-02-13 14:44 UTC, amjltc295 commented on backend/app/app/crud/crud_metrics.py
> +import dateutil.parser
This is a third-party module; please move it to be with sqlalchemy

2021-02-13 14:45 UTC, amjltc295 commented on backend/app/app/crud/crud_metrics.py
> +from datetime import datetime
Please merge with line 1

2021-02-14 10:48 UTC, ChiaEnC commented on website/src/sagas/metricsSaga.js
> +} else if (error) {
do you mean line 40's } ?

2021-02-15 04:23 UTC, amjltc295 requested changes

2021-02-15 04:27 UTC, ChiaEnC commented on backend/app/app/crud/crud_metrics.py
> +            Customer.platform_i == metrics_in.platform_id,
I've changed the typo error and pushed ?

2021-02-15 08:30 UTC, amjltc295 requested changes

2021-02-15 08:30 UTC, amjltc295 commented on backend/app/app/crud/crud_metrics.py
> +import dateutil.parser
Please remove unnecessary changes

2021-02-15 08:30 UTC, amjltc295 commented on website/src/logged_in/views/dashboard/Dashboard.js
> +      <div className={classes.firstSection}> Interval : {params.interval} ms</div>
It is not ms

2021-02-15 08:30 UTC, amjltc295 commented on website/src/logged_in/views/dashboard/Dashboard.js
> +      <div className={classes.firstSection}> Growth {metrics ? metrics.growth : null} </div>
Please include start_time as well

2021-02-15 08:30 UTC, amjltc295 commented on website/src/sagas/metricsSaga.js
> +    console.log(platformId)
If you want to keep the log here, add "platformID:"

2021-02-15 08:32 UTC, amjltc295 commented on website/src/logged_in/views/dashboard/Dashboard.js
> +      <div className={classes.firstSection}> Interval : {params.interval} ms</div>
Should be seconds

2021-02-15 08:41 UTC, ChiaEnC commented on website/src/sagas/metricsSaga.js
> +    console.log(platformId)
deleted ! It's for debugging.

2021-02-15 09:23 UTC, amjltc295 commented on backend/app/app/crud/crud_metrics.py
> +
This too...

2021-02-16 08:35 UTC, amjltc295 approved these changes
LGTM

2021-02-16 08:35 UTC, merged