Dako 135 fe fix homepage being blank after login
DakoData/DakoData pull request #18
Opened 2021-02-11 05:00 UTC by KalleChen

## Why do we need this PR?
* Fix homepage being blank

## How did you address the issue?
* Remove claerLocation() while login
* Add PrivateRoute
* Reconstruct router in App.js

<br />  

> #### PR readiness check list
> - [x] Did it pass the Flake8/Standard JS check?
> - [x] Did you test this PR?  
> - [x] Did you explain the changes clearly?
> - [x] Does the PR title reference a Jira issue for the correct project (at the beginning of the title)?

2021-02-11 07:07 UTC, ChiaEnC approved these changes

2021-02-13 14:11 UTC, amjltc295 requested changes
After log in, I can access home page but it will still show register and login button. Do you have time to fix that in this ticket? If not, please create another ticket to fix it.

2021-02-14 10:24 UTC, KalleChen commented
@amjltc295 I change the home page into PrivateRoute.  Base on the design now,  I think the user is not allowed to access the home page after login. If the UI change, I would do it on another ticket.

2021-02-14 11:23 UTC, amjltc295 approved these changes

2021-02-14 11:23 UTC, merged