Dako 157 fe update default dashboard time
DakoData/DakoData pull request #25
Opened 2021-02-19 13:35 UTC by ChiaEnC

## Why do we need this PR?
* Modify backend for showing start time : 2 weeks from latest data time 

## How did you address the issue?
* query customer events data time and sort to get the latest time 

<br />  

> #### PR readiness check list
> - [ ] Did it pass the Flake8/Standard JS check?
> - [ ] Did you test this PR?  
> - [ ] Did you explain the changes clearly?
> - [ ] Does the PR title reference a Jira issue for the correct project (at the beginning of the title)?

2021-02-20 03:28 UTC, amjltc295 requested changes
get_start_time_from_latest_data_time() will result in misleading behavior (start_time is not used). This logic should be implemented in front-end

2021-02-21 02:04 UTC, amjltc295 requested changes

2021-02-21 02:04 UTC, amjltc295 commented on backend/app/app/api/api_v1/endpoints/utils.py
> +    Get latest created time from customer or customer events.
You have to check users

2021-02-21 02:04 UTC, amjltc295 commented on backend/app/app/api/api_v1/endpoints/utils.py
> +    Get latest created time from customer or customer events.
And return error message if None

2021-02-21 02:04 UTC, amjltc295 commented on backend/app/app/api/api_v1/endpoints/utils.py
> +@router.get("/latest-data-time/", response_model=schemas.Msg)
We should use another response model. customer_entry and customer_event_entry should be both returned

2021-02-21 02:04 UTC, amjltc295 commented on website/src/logged_in/views/dashboard/Dashboard.js
> +      today.setDate(today.getDate() + 14)
-14

2021-02-21 13:58 UTC, amjltc295 requested changes
No module named 'app.schemas.latest_data_time'
You probably forgot to commit this file

2021-02-21 14:00 UTC, amjltc295 commented on backend/app/app/api/api_v1/endpoints/utils.py
> +    times = {}
Could you rename it as result/response?

2021-02-22 03:28 UTC, amjltc295 requested changes
Still not working if there's no customer/customer_events. Did you really test it?

2021-02-22 03:28 UTC, amjltc295 commented on backend/app/app/api/api_v1/endpoints/utils.py
> +    response["latest_customer_data_time"] = ""
If you pass "" to Optional[datetime], it would still fail. You should pass None

2021-02-22 03:28 UTC, amjltc295 commented on backend/app/app/api/api_v1/endpoints/utils.py
> +        response["latest_customer_event_data_time"] = str(latest_customer_event_entry.created_at)
(Optional) These lines could be 
response["latest_customer_event_data_time"] = (
    str(latest_customer_event_entry.created_at)
    if latest_customer_event_entry is not None 
    else None
)

2021-02-22 03:29 UTC, amjltc295 commented on backend/app/app/schemas/latest_data_time.py
> +
This does not pass Flake8. Two empty lines between packages and functions

2021-02-23 10:28 UTC, KalleChen approved these changes

2021-02-23 14:42 UTC, amjltc295 approved these changes

2021-02-23 14:44 UTC, merged