create api for company_name and phone number and connect front end to…
DakoData/DakoData pull request #29
Opened 2021-02-28 15:24 UTC by ChiaEnC

… this api

## Why do we need this PR?
* Save company name and phone in back end and make front end phone and company name required

## How did you address the issue?
* implement backend api and add new columns, including db migration. Also, I connect front end this api and handle basic phone format validation.

<br />  

> #### PR readiness check list
> - [ ] Did it pass the Flake8/Standard JS check?
> - [ ] Did you test this PR?  
> - [ ] Did you explain the changes clearly?
> - [ ] Does the PR title reference a Jira issue for the correct project (at the beginning of the title)?

2021-03-01 06:18 UTC, amjltc295 requested changes

2021-03-01 06:18 UTC, amjltc295 commented on website/src/logged_in/views/product/ProductSetting.js
> +    if (user.company_name.length !== 0 || user.phone_number.length !== 0) {
Default user. company_name and user.phone_number are null. This would cause errors

2021-03-01 06:18 UTC, amjltc295 commented on website/src/logged_in/views/product/ProductSetting.js
> +    if (user.company_name.length !== 0 || user.phone_number.length !== 0) {
![Uploading Screen Shot 2021-03-01 at 2.14.37 PM.png…]()

2021-03-02 15:41 UTC, ChiaEnC commented on website/src/logged_in/views/product/ProductSetting.js
> +    if (user.company_name.length !== 0 || user.phone_number.length !== 0) {
solved

2021-03-03 01:33 UTC, KalleChen approved these changes

2021-03-03 14:30 UTC, amjltc295 approved these changes

2021-03-03 14:30 UTC, merged