Dako 189 fe create login/register page
DakoData/DakoData pull request #32
Opened 2021-03-10 08:11 UTC by KalleChen

# PR Template
## Why do we need this PR?
* Rebuild login/register pages

## How did you address the issue?
* Redesign the login/register pages
* Change Routing for only /login and /register
* Add email and password check

<br />  

> ## PR readiness check list
> - [x] Did it pass the Standard JS check?
> - [x] Did you test this PR?  
> - [x] Did you explain the changes clearly?
> - [x] Does the PR title reference a Jira issue for the correct project (at the beginning of the title)?

2021-03-11 06:48 UTC, amjltc295 requested changes
Good job! There are still some problems to fix. Also, could you change the icon for web tag to our logo?

2021-03-11 06:48 UTC, amjltc295 commented on website/src/logged_out/components/register_login/RegisterDialog.js
> +                registerState.message ===
Checking with message is not a very good practice .. we may nee to re-design this API

2021-03-11 06:48 UTC, amjltc295 commented on website/src/logged_out/components/register_login/LoginDialog.js
> +        slogan='(Slogan)'
Please confirm with @Yuhsin to write something here or leave it blank

2021-03-11 06:48 UTC, amjltc295 commented on website/src/logged_out/components/register_login/RegisterDialog.js
> +                  隱私權條款
I cannot open this dialog

2021-03-11 10:57 UTC, KalleChen commented on website/src/logged_out/components/register_login/RegisterDialog.js
> +                  隱私權條款
The design team said that this dialog hasn't been designed yet, so just keep this text link disabled.

2021-03-11 10:59 UTC, KalleChen commented on website/src/logged_out/components/register_login/RegisterDialog.js
> +                registerState.message ===
Just changed the default error detail for the register add show the message directly below the email field.

2021-03-11 10:59 UTC, KalleChen commented on website/src/logged_out/components/register_login/LoginDialog.js
> +        slogan='(Slogan)'
Fixed

2021-03-12 06:00 UTC, amjltc295 approved these changes

2021-03-12 06:01 UTC, merged